// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqwutsiepmxvqwtjmzch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxd3V0c2llcG14dnF3dGptemNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODgyMTIsImV4cCI6MjA2OTI2NDIxMn0._5gTMcsDYXKXmi-1UblU4U7edWd3TjPVwoBt9eFMbAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});